## Basic Configuration
baseurl = "/"
theme = "hyde-hyde"
languageCode = "en"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
title = "Daniel Redondo"
paginate = 7
# paginatepath = "page"

     
## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
 googleAnalytics = "UA-129757599-1"
# enableRobotsTXT = true

## Site Settings
[params]
    author = "Daniel Redondo"
    description = "danielredondo.com"
    authorimage = "/img/piramide.png"
    dateformat = "2006-01-02"
    # themeColor = "theme-custom-drs" # Para cambiar colores, ir a:
                                      # \themes\hyde-hyde\assets\scss\hyde-hyde\_variables.scss
    highlightjs = true
    highlightjsstyle = "github"
    highlightjslanguages = ["r"]
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"
    # layoutReverse = true
    # sidebarSticky = true

## Social Accounts
[params.social]
    github = "danielredondo"
    # instagram = "<username>"
    # xing = "<username>"
    linkedin = "dredondosanchez"
    twitter = "dredondosanchez"
    # facebook = "<username>"
    # stackoverflow = "<username>"
    # email = "<username>"

## Main Menu
[[menu.main]]
    name = "BLOG"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "PUBLICACIONES"
    weight = 110
    identifier = "publicaciones"
    url = "/publicaciones/"
[[menu.main]]
    name = "APLICACIONES WEB"
    weight = 130
    identifier = "aplicaciones"
    url = "/aplicaciones/"
[[menu.main]]
    name = "SOBRE M√ç"
    identifier = "about"
    weight = 200
    url = "/about/"